package com.TransitApp.Modeles;
// Generated 7 févr. 2023, 23:03:37 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name = "categorie", catalog = "transitbd")
public class Categorie implements java.io.Serializable {

	private Integer idcategorie;
	private String libelecategorie;

	public Categorie() {
	}

	public Categorie(String libelecategorie) {
		this.libelecategorie = libelecategorie;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDCATEGORIE", unique = true, nullable = false)
	public Integer getIdcategorie() {
		return this.idcategorie;
	}

	public void setIdcategorie(Integer idcategorie) {
		this.idcategorie = idcategorie;
	}

	@Column(name = "LIBELECATEGORIE", length = 100)
	public String getLibelecategorie() {
		return this.libelecategorie;
	}

	public void setLibelecategorie(String libelecategorie) {
		this.libelecategorie = libelecategorie;
	}

}
