package com.TransitApp.Modeles;
// Generated 7 févr. 2023, 23:03:37 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "transitbd")
public class Client implements java.io.Serializable {

	private Integer idclient;
	private String nomclient;
	private String prenomclient;
	private Date datenaissanceclient;
	private String civilte;
	private String adresseclient;
	private String codepostal;
	private String villeclient;
	private String telephoneclient;
	private String emailclient;

	public Client() {
	}

	public Client(String nomclient, String prenomclient, Date datenaissanceclient, String adresseclient,
			String telephoneclient, String emailclient) {
		this.nomclient = nomclient;
		this.prenomclient = prenomclient;
		this.datenaissanceclient = datenaissanceclient;
		this.adresseclient = adresseclient;
		this.telephoneclient = telephoneclient;
		this.emailclient = emailclient;
	}

	public Client(String nomclient, String prenomclient, Date datenaissanceclient, String civilte, String adresseclient,
			String codepostal, String villeclient, String telephoneclient, String emailclient) {
		this.nomclient = nomclient;
		this.prenomclient = prenomclient;
		this.datenaissanceclient = datenaissanceclient;
		this.civilte = civilte;
		this.adresseclient = adresseclient;
		this.codepostal = codepostal;
		this.villeclient = villeclient;
		this.telephoneclient = telephoneclient;
		this.emailclient = emailclient;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDCLIENT", unique = true, nullable = false)
	public Integer getIdclient() {
		return this.idclient;
	}

	public void setIdclient(Integer idclient) {
		this.idclient = idclient;
	}

	@Column(name = "NOMCLIENT", nullable = false, length = 50)
	public String getNomclient() {
		return this.nomclient;
	}

	public void setNomclient(String nomclient) {
		this.nomclient = nomclient;
	}

	@Column(name = "PRENOMCLIENT", nullable = false, length = 100)
	public String getPrenomclient() {
		return this.prenomclient;
	}

	public void setPrenomclient(String prenomclient) {
		this.prenomclient = prenomclient;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATENAISSANCECLIENT", nullable = false, length = 10)
	public Date getDatenaissanceclient() {
		return this.datenaissanceclient;
	}

	public void setDatenaissanceclient(Date datenaissanceclient) {
		this.datenaissanceclient = datenaissanceclient;
	}

	@Column(name = "CIVILTE", length = 10)
	public String getCivilte() {
		return this.civilte;
	}

	public void setCivilte(String civilte) {
		this.civilte = civilte;
	}

	@Column(name = "ADRESSECLIENT", nullable = false, length = 100)
	public String getAdresseclient() {
		return this.adresseclient;
	}

	public void setAdresseclient(String adresseclient) {
		this.adresseclient = adresseclient;
	}

	@Column(name = "CODEPOSTAL", length = 100)
	public String getCodepostal() {
		return this.codepostal;
	}

	public void setCodepostal(String codepostal) {
		this.codepostal = codepostal;
	}

	@Column(name = "VILLECLIENT", length = 100)
	public String getVilleclient() {
		return this.villeclient;
	}

	public void setVilleclient(String villeclient) {
		this.villeclient = villeclient;
	}

	@Column(name = "TELEPHONECLIENT", nullable = false, length = 100)
	public String getTelephoneclient() {
		return this.telephoneclient;
	}

	public void setTelephoneclient(String telephoneclient) {
		this.telephoneclient = telephoneclient;
	}

	@Column(name = "EMAILCLIENT", nullable = false, length = 150)
	public String getEmailclient() {
		return this.emailclient;
	}

	public void setEmailclient(String emailclient) {
		this.emailclient = emailclient;
	}

}
