package com.TransitApp.Modeles;
// Generated 4 févr. 2023, 18:30:13 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Contenir1 generated by hbm2java
 */
@Entity
@Table(name = "contenir1", catalog = "transitbd")
public class Contenir1 implements java.io.Serializable {

	private Contenir1Id id;
	private String idcommandefournisseur;
	private Integer quantitearticle;
	private Float cout;

	public Contenir1() {
	}

	public Contenir1(Contenir1Id id) {
		this.id = id;
	}

	public Contenir1(Contenir1Id id, String idcommandefournisseur, Integer quantitearticle, Float cout) {
		this.id = id;
		this.idcommandefournisseur = idcommandefournisseur;
		this.quantitearticle = quantitearticle;
		this.cout = cout;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idproduit", column = @Column(name = "IDPRODUIT", nullable = false)),
			@AttributeOverride(name = "idcommandefourn", column = @Column(name = "IDCOMMANDEFOURN", nullable = false)) })
	public Contenir1Id getId() {
		return this.id;
	}

	public void setId(Contenir1Id id) {
		this.id = id;
	}

	@Column(name = "IDCOMMANDEFOURNISSEUR", length = 20)
	public String getIdcommandefournisseur() {
		return this.idcommandefournisseur;
	}

	public void setIdcommandefournisseur(String idcommandefournisseur) {
		this.idcommandefournisseur = idcommandefournisseur;
	}

	@Column(name = "QUANTITEARTICLE")
	public Integer getQuantitearticle() {
		return this.quantitearticle;
	}

	public void setQuantitearticle(Integer quantitearticle) {
		this.quantitearticle = quantitearticle;
	}

	@Column(name = "COUT", precision = 8)
	public Float getCout() {
		return this.cout;
	}

	public void setCout(Float cout) {
		this.cout = cout;
	}

}
