package com.TransitApp.Modeles;
// Generated 4 févr. 2023, 18:30:13 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Contenir1Id generated by hbm2java
 */
@Embeddable
public class Contenir1Id implements java.io.Serializable {

	private int idproduit;
	private int idcommandefourn;

	public Contenir1Id() {
	}

	public Contenir1Id(int idproduit, int idcommandefourn) {
		this.idproduit = idproduit;
		this.idcommandefourn = idcommandefourn;
	}

	@Column(name = "IDPRODUIT", nullable = false)
	public int getIdproduit() {
		return this.idproduit;
	}

	public void setIdproduit(int idproduit) {
		this.idproduit = idproduit;
	}

	@Column(name = "IDCOMMANDEFOURN", nullable = false)
	public int getIdcommandefourn() {
		return this.idcommandefourn;
	}

	public void setIdcommandefourn(int idcommandefourn) {
		this.idcommandefourn = idcommandefourn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Contenir1Id))
			return false;
		Contenir1Id castOther = (Contenir1Id) other;

		return (this.getIdproduit() == castOther.getIdproduit())
				&& (this.getIdcommandefourn() == castOther.getIdcommandefourn());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdproduit();
		result = 37 * result + this.getIdcommandefourn();
		return result;
	}

}
