package com.TransitApp.Modeles;
// Generated 4 févr. 2023, 18:30:13 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContenirId generated by hbm2java
 */
@Embeddable
public class ContenirId implements java.io.Serializable {

	private int idproduit;
	private int identrepot;

	public ContenirId() {
	}

	public ContenirId(int idproduit, int identrepot) {
		this.idproduit = idproduit;
		this.identrepot = identrepot;
	}

	@Column(name = "IDPRODUIT", nullable = false)
	public int getIdproduit() {
		return this.idproduit;
	}

	public void setIdproduit(int idproduit) {
		this.idproduit = idproduit;
	}

	@Column(name = "IDENTREPOT", nullable = false)
	public int getIdentrepot() {
		return this.identrepot;
	}

	public void setIdentrepot(int identrepot) {
		this.identrepot = identrepot;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContenirId))
			return false;
		ContenirId castOther = (ContenirId) other;

		return (this.getIdproduit() == castOther.getIdproduit()) && (this.getIdentrepot() == castOther.getIdentrepot());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdproduit();
		result = 37 * result + this.getIdentrepot();
		return result;
	}

}
