package com.TransitApp.Modeles;
// Generated 12 févr. 2023, 10:07:19 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Contenir2Id generated by hbm2java
 */
@Embeddable
public class Contenir2Id implements java.io.Serializable {

	private int idproduit;
	private String idcommandeclient;

	public Contenir2Id() {
	}

	public Contenir2Id(int idproduit, String idcommandeclient) {
		this.idproduit = idproduit;
		this.idcommandeclient = idcommandeclient;
	}

	@Column(name = "IDPRODUIT", nullable = false)
	public int getIdproduit() {
		return this.idproduit;
	}

	public void setIdproduit(int idproduit) {
		this.idproduit = idproduit;
	}

	@Column(name = "IDCOMMANDECLIENT", nullable = false, length = 40)
	public String getIdcommandeclient() {
		return this.idcommandeclient;
	}

	public void setIdcommandeclient(String idcommandeclient) {
		this.idcommandeclient = idcommandeclient;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Contenir2Id))
			return false;
		Contenir2Id castOther = (Contenir2Id) other;

		return (this.getIdproduit() == castOther.getIdproduit())
				&& ((this.getIdcommandeclient() == castOther.getIdcommandeclient())
						|| (this.getIdcommandeclient() != null && castOther.getIdcommandeclient() != null
								&& this.getIdcommandeclient().equals(castOther.getIdcommandeclient())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdproduit();
		result = 37 * result + (getIdcommandeclient() == null ? 0 : this.getIdcommandeclient().hashCode());
		return result;
	}

}
