package com.TransitApp.Modeles;
// Generated 7 févr. 2023, 23:03:37 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CreerId generated by hbm2java
 */
@Embeddable
public class CreerId implements java.io.Serializable {

	private int idmanager;
	private int idordremission;

	public CreerId() {
	}

	public CreerId(int idmanager, int idordremission) {
		this.idmanager = idmanager;
		this.idordremission = idordremission;
	}

	@Column(name = "IDMANAGER", nullable = false)
	public int getIdmanager() {
		return this.idmanager;
	}

	public void setIdmanager(int idmanager) {
		this.idmanager = idmanager;
	}

	@Column(name = "IDORDREMISSION", nullable = false)
	public int getIdordremission() {
		return this.idordremission;
	}

	public void setIdordremission(int idordremission) {
		this.idordremission = idordremission;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CreerId))
			return false;
		CreerId castOther = (CreerId) other;

		return (this.getIdmanager() == castOther.getIdmanager())
				&& (this.getIdordremission() == castOther.getIdordremission());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdmanager();
		result = 37 * result + this.getIdordremission();
		return result;
	}

}
