package com.TransitApp.Modeles;
// Generated 12 févr. 2023, 10:07:19 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Creer generated by hbm2java
 */
@Entity
@Table(name = "creer", catalog = "transitbd")
public class Creer implements java.io.Serializable {

	private CreerId id;

	public Creer() {
	}

	public Creer(CreerId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idmanager", column = @Column(name = "IDMANAGER", nullable = false)),
			@AttributeOverride(name = "idordremission", column = @Column(name = "IDORDREMISSION", nullable = false)) })
	public CreerId getId() {
		return this.id;
	}

	public void setId(CreerId id) {
		this.id = id;
	}

}
