package com.TransitApp.Modeles;
// Generated 11 févr. 2023, 19:25:20 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EffectuerId generated by hbm2java
 */
@Embeddable
public class EffectuerId implements java.io.Serializable {

	private String idcommandeclient;
	private int idclient;

	public EffectuerId() {
	}

	public EffectuerId(String idcommandeclient, int idclient) {
		this.idcommandeclient = idcommandeclient;
		this.idclient = idclient;
	}

	@Column(name = "IDCOMMANDECLIENT", nullable = false, length = 40)
	public String getIdcommandeclient() {
		return this.idcommandeclient;
	}

	public void setIdcommandeclient(String idcommandeclient) {
		this.idcommandeclient = idcommandeclient;
	}

	@Column(name = "IDCLIENT", nullable = false)
	public int getIdclient() {
		return this.idclient;
	}

	public void setIdclient(int idclient) {
		this.idclient = idclient;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EffectuerId))
			return false;
		EffectuerId castOther = (EffectuerId) other;

		return ((this.getIdcommandeclient() == castOther.getIdcommandeclient())
				|| (this.getIdcommandeclient() != null && castOther.getIdcommandeclient() != null
						&& this.getIdcommandeclient().equals(castOther.getIdcommandeclient())))
				&& (this.getIdclient() == castOther.getIdclient());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdcommandeclient() == null ? 0 : this.getIdcommandeclient().hashCode());
		result = 37 * result + this.getIdclient();
		return result;
	}

}
