package com.TransitApp.Modeles;
// Generated 4 févr. 2023, 18:30:13 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Enregistrer generated by hbm2java
 */
@Entity
@Table(name = "enregistrer", catalog = "transitbd")
public class Enregistrer implements java.io.Serializable {

	private EnregistrerId id;
	private Date dateenregistrement;

	public Enregistrer() {
	}

	public Enregistrer(EnregistrerId id) {
		this.id = id;
	}

	public Enregistrer(EnregistrerId id, Date dateenregistrement) {
		this.id = id;
		this.dateenregistrement = dateenregistrement;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idmanager", column = @Column(name = "IDMANAGER", nullable = false)),
			@AttributeOverride(name = "idcommandeclient", column = @Column(name = "IDCOMMANDECLIENT", nullable = false, length = 40)) })
	public EnregistrerId getId() {
		return this.id;
	}

	public void setId(EnregistrerId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEENREGISTREMENT", length = 10)
	public Date getDateenregistrement() {
		return this.dateenregistrement;
	}

	public void setDateenregistrement(Date dateenregistrement) {
		this.dateenregistrement = dateenregistrement;
	}

}
