package com.TransitApp.Modeles;
// Generated 7 févr. 2023, 23:03:37 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EnregistrerId generated by hbm2java
 */
@Embeddable
public class EnregistrerId implements java.io.Serializable {

	private int idmanager;
	private String idcommandeclient;

	public EnregistrerId() {
	}

	public EnregistrerId(int idmanager, String idcommandeclient) {
		this.idmanager = idmanager;
		this.idcommandeclient = idcommandeclient;
	}

	@Column(name = "IDMANAGER", nullable = false)
	public int getIdmanager() {
		return this.idmanager;
	}

	public void setIdmanager(int idmanager) {
		this.idmanager = idmanager;
	}

	@Column(name = "IDCOMMANDECLIENT", nullable = false, length = 40)
	public String getIdcommandeclient() {
		return this.idcommandeclient;
	}

	public void setIdcommandeclient(String idcommandeclient) {
		this.idcommandeclient = idcommandeclient;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EnregistrerId))
			return false;
		EnregistrerId castOther = (EnregistrerId) other;

		return (this.getIdmanager() == castOther.getIdmanager())
				&& ((this.getIdcommandeclient() == castOther.getIdcommandeclient())
						|| (this.getIdcommandeclient() != null && castOther.getIdcommandeclient() != null
								&& this.getIdcommandeclient().equals(castOther.getIdcommandeclient())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdmanager();
		result = 37 * result + (getIdcommandeclient() == null ? 0 : this.getIdcommandeclient().hashCode());
		return result;
	}

}
