package com.TransitApp.Modeles;
// Generated 11 févr. 2023, 19:25:20 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Entrepot generated by hbm2java
 */
@Entity
@Table(name = "entrepot", catalog = "transitbd")
public class Entrepot implements java.io.Serializable {

	private Integer identrepot;
	private String nomentrepot;
	private String numeroentrepot;
	private Float capacitstockage;
	private String unitemesurcapacite;

	public Entrepot() {
	}

	public Entrepot(int identrepot,String nomentrepot, String numeroentrepot, Float capacitstockage, String unitemesurcapacite) {
		this.identrepot = identrepot;
		this.nomentrepot = nomentrepot;
		this.numeroentrepot = numeroentrepot;
		this.capacitstockage = capacitstockage;
		this.unitemesurcapacite = unitemesurcapacite;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDENTREPOT", unique = true, nullable = false)
	public Integer getIdentrepot() {
		return this.identrepot;
	}

	public void setIdentrepot(Integer identrepot) {
		this.identrepot = identrepot;
	}

	@Column(name = "NOMENTREPOT", length = 50)
	public String getNomentrepot() {
		return this.nomentrepot;
	}

	public void setNomentrepot(String nomentrepot) {
		this.nomentrepot = nomentrepot;
	}

	@Column(name = "NUMEROENTREPOT", length = 100)
	public String getNumeroentrepot() {
		return this.numeroentrepot;
	}

	public void setNumeroentrepot(String numeroentrepot) {
		this.numeroentrepot = numeroentrepot;
	}

	@Column(name = "CAPACITSTOCKAGE", precision = 12, scale = 0)
	public Float getCapacitstockage() {
		return this.capacitstockage;
	}

	public void setCapacitstockage(Float capacitstockage) {
		this.capacitstockage = capacitstockage;
	}

	@Column(name = "UNITEMESURCAPACITE", length = 10)
	public String getUnitemesurcapacite() {
		return this.unitemesurcapacite;
	}

	public void setUnitemesurcapacite(String unitemesurcapacite) {
		this.unitemesurcapacite = unitemesurcapacite;
	}

}
