package com.TransitApp.Modeles;
// Generated 11 févr. 2023, 19:25:20 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Manager generated by hbm2java
 */
@Entity
@Table(name = "manager", catalog = "transitbd")
public class Manager implements java.io.Serializable {

	private Integer idmanager;
	private int idadmin;
	private String nommanager;
	private String prenommanager;
	private String civilite;
	private Date datedebutembauche;
	private Date datefinembauche;
	private Float salaire;
	private String fonction;

	public Manager() {
	}

	public Manager(int idadmin) {
		this.idadmin = idadmin;
	}

	public Manager(int idadmin, String nommanager, String prenommanager, String civilite, Date datedebutembauche,
			Date datefinembauche, Float salaire, String fonction) {
		this.idadmin = idadmin;
		this.nommanager = nommanager;
		this.prenommanager = prenommanager;
		this.civilite = civilite;
		this.datedebutembauche = datedebutembauche;
		this.datefinembauche = datefinembauche;
		this.salaire = salaire;
		this.fonction = fonction;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDMANAGER", unique = true, nullable = false)
	public Integer getIdmanager() {
		return this.idmanager;
	}

	public void setIdmanager(Integer idmanager) {
		this.idmanager = idmanager;
	}

	@Column(name = "IDADMIN", nullable = false)
	public int getIdadmin() {
		return this.idadmin;
	}

	public void setIdadmin(int idadmin) {
		this.idadmin = idadmin;
	}

	@Column(name = "NOMMANAGER", length = 25)
	public String getNommanager() {
		return this.nommanager;
	}

	public void setNommanager(String nommanager) {
		this.nommanager = nommanager;
	}

	@Column(name = "PRENOMMANAGER", length = 40)
	public String getPrenommanager() {
		return this.prenommanager;
	}

	public void setPrenommanager(String prenommanager) {
		this.prenommanager = prenommanager;
	}

	@Column(name = "CIVILITE", length = 10)
	public String getCivilite() {
		return this.civilite;
	}

	public void setCivilite(String civilite) {
		this.civilite = civilite;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEDEBUTEMBAUCHE", length = 10)
	public Date getDatedebutembauche() {
		return this.datedebutembauche;
	}

	public void setDatedebutembauche(Date datedebutembauche) {
		this.datedebutembauche = datedebutembauche;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEFINEMBAUCHE", length = 10)
	public Date getDatefinembauche() {
		return this.datefinembauche;
	}

	public void setDatefinembauche(Date datefinembauche) {
		this.datefinembauche = datefinembauche;
	}

	@Column(name = "SALAIRE", precision = 12, scale = 0)
	public Float getSalaire() {
		return this.salaire;
	}

	public void setSalaire(Float salaire) {
		this.salaire = salaire;
	}

	@Column(name = "FONCTION", length = 30)
	public String getFonction() {
		return this.fonction;
	}

	public void setFonction(String fonction) {
		this.fonction = fonction;
	}

}
