package com.TransitApp.Modeles;
// Generated 12 févr. 2023, 10:07:19 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name = "produit", catalog = "transitbd")
public class Produit implements java.io.Serializable {

	private Integer idproduit;
	private int idfournisseur;
	private int idcategorie;
	private String nomproduit;
	private Float prixunitaire;
	private Float poids;
	private String poidunitemesurecode;
	private String numeroproduit;
	private String description;
	private Date dateajout;
	private int quantite;

	public Produit() {
	}

	public Produit(int idfournisseur, int idcategorie, String numeroproduit, int quantite) {
		this.idfournisseur = idfournisseur;
		this.idcategorie = idcategorie;
		this.numeroproduit = numeroproduit;
		this.quantite = quantite;
	}

	public Produit(int idproduit,int idfournisseur, int idcategorie, String nomproduit, Float prixunitaire, Float poids,
			String poidunitemesurecode, String numeroproduit, String description, Date dateajout, int quantite) {
		this.idproduit = idproduit;
		this.idfournisseur = idfournisseur;
		this.idcategorie = idcategorie;
		this.nomproduit = nomproduit;
		this.prixunitaire = prixunitaire;
		this.poids = poids;
		this.poidunitemesurecode = poidunitemesurecode;
		this.numeroproduit = numeroproduit;
		this.description = description;
		this.dateajout = dateajout;
		this.quantite = quantite;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDPRODUIT", unique = true, nullable = false)
	public Integer getIdproduit() {
		return this.idproduit;
	}

	public void setIdproduit(Integer idproduit) {
		this.idproduit = idproduit;
	}

	@Column(name = "IDFOURNISSEUR", nullable = false)
	public int getIdfournisseur() {
		return this.idfournisseur;
	}

	public void setIdfournisseur(int idfournisseur) {
		this.idfournisseur = idfournisseur;
	}

	@Column(name = "IDCATEGORIE", nullable = false)
	public int getIdcategorie() {
		return this.idcategorie;
	}

	public void setIdcategorie(int idcategorie) {
		this.idcategorie = idcategorie;
	}

	@Column(name = "NOMPRODUIT", length = 70)
	public String getNomproduit() {
		return this.nomproduit;
	}

	public void setNomproduit(String nomproduit) {
		this.nomproduit = nomproduit;
	}

	@Column(name = "PRIXUNITAIRE", precision = 8)
	public Float getPrixunitaire() {
		return this.prixunitaire;
	}

	public void setPrixunitaire(Float prixunitaire) {
		this.prixunitaire = prixunitaire;
	}

	@Column(name = "POIDS", precision = 12, scale = 0)
	public Float getPoids() {
		return this.poids;
	}

	public void setPoids(Float poids) {
		this.poids = poids;
	}

	@Column(name = "POIDUNITEMESURECODE", length = 10)
	public String getPoidunitemesurecode() {
		return this.poidunitemesurecode;
	}

	public void setPoidunitemesurecode(String poidunitemesurecode) {
		this.poidunitemesurecode = poidunitemesurecode;
	}

	@Column(name = "NUMEROPRODUIT", nullable = false, length = 50)
	public String getNumeroproduit() {
		return this.numeroproduit;
	}

	public void setNumeroproduit(String numeroproduit) {
		this.numeroproduit = numeroproduit;
	}

	@Column(name = "DESCRIPTION", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEAJOUT", length = 10)
	public Date getDateajout() {
		return this.dateajout;
	}

	public void setDateajout(Date dateajout) {
		this.dateajout = dateajout;
	}

	@Column(name = "QUANTITE", nullable = false)
	public int getQuantite() {
		return this.quantite;
	}

	public void setQuantite(int quantite) {
		this.quantite = quantite;
	}

}
