package com.TransitApp.Modeles;
// Generated 4 févr. 2023, 18:30:13 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name = "produit", catalog = "transitbd")
public class Produit implements java.io.Serializable {

	private Integer idproduit;
	private String nomproduit;
	private Float prixunitaire;
	private Float poids;
	private String poidunitemesurecode;
	private String numeroproduit;
	private String description;
	private int idcategorie;

	public Produit() {
	}

	public Produit(String numeroproduit, int idcategorie) {
		this.numeroproduit = numeroproduit;
		this.idcategorie = idcategorie;
	}

	public Produit(String nomproduit, Float prixunitaire, Float poids, String poidunitemesurecode, String numeroproduit,
			String description, int idcategorie) {
		this.nomproduit = nomproduit;
		this.prixunitaire = prixunitaire;
		this.poids = poids;
		this.poidunitemesurecode = poidunitemesurecode;
		this.numeroproduit = numeroproduit;
		this.description = description;
		this.idcategorie = idcategorie;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDPRODUIT", unique = true, nullable = false)
	public Integer getIdproduit() {
		return this.idproduit;
	}

	public void setIdproduit(Integer idproduit) {
		this.idproduit = idproduit;
	}

	@Column(name = "NOMPRODUIT", length = 70)
	public String getNomproduit() {
		return this.nomproduit;
	}

	public void setNomproduit(String nomproduit) {
		this.nomproduit = nomproduit;
	}

	@Column(name = "PRIXUNITAIRE", precision = 8)
	public Float getPrixunitaire() {
		return this.prixunitaire;
	}

	public void setPrixunitaire(Float prixunitaire) {
		this.prixunitaire = prixunitaire;
	}

	@Column(name = "POIDS", precision = 12, scale = 0)
	public Float getPoids() {
		return this.poids;
	}

	public void setPoids(Float poids) {
		this.poids = poids;
	}

	@Column(name = "POIDUNITEMESURECODE", length = 10)
	public String getPoidunitemesurecode() {
		return this.poidunitemesurecode;
	}

	public void setPoidunitemesurecode(String poidunitemesurecode) {
		this.poidunitemesurecode = poidunitemesurecode;
	}

	@Column(name = "NUMEROPRODUIT", nullable = false, length = 50)
	public String getNumeroproduit() {
		return this.numeroproduit;
	}

	public void setNumeroproduit(String numeroproduit) {
		this.numeroproduit = numeroproduit;
	}

	@Column(name = "DESCRIPTION", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "IDCATEGORIE", nullable = false)
	public int getIdcategorie() {
		return this.idcategorie;
	}

	public void setIdcategorie(int idcategorie) {
		this.idcategorie = idcategorie;
	}

}
