package com.TransitApp.Modeles;
// Generated 4 févr. 2023, 18:30:13 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Resporeapro generated by hbm2java
 */
@Entity
@Table(name = "resporeapro", catalog = "transitbd")
public class Resporeapro implements java.io.Serializable {

	private Integer idresporeapro;
	private int idadmin;
	private String nomresporeapro;
	private String prenomresporeapro;
	private String civilite;
	private Date datedebutembauche;
	private Date datefinembauche;
	private Float salaire;
	private String fonction;

	public Resporeapro() {
	}

	public Resporeapro(int idadmin) {
		this.idadmin = idadmin;
	}

	public Resporeapro(int idadmin, String nomresporeapro, String prenomresporeapro, String civilite,
			Date datedebutembauche, Date datefinembauche, Float salaire, String fonction) {
		this.idadmin = idadmin;
		this.nomresporeapro = nomresporeapro;
		this.prenomresporeapro = prenomresporeapro;
		this.civilite = civilite;
		this.datedebutembauche = datedebutembauche;
		this.datefinembauche = datefinembauche;
		this.salaire = salaire;
		this.fonction = fonction;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDRESPOREAPRO", unique = true, nullable = false)
	public Integer getIdresporeapro() {
		return this.idresporeapro;
	}

	public void setIdresporeapro(Integer idresporeapro) {
		this.idresporeapro = idresporeapro;
	}

	@Column(name = "IDADMIN", nullable = false)
	public int getIdadmin() {
		return this.idadmin;
	}

	public void setIdadmin(int idadmin) {
		this.idadmin = idadmin;
	}

	@Column(name = "NOMRESPOREAPRO", length = 25)
	public String getNomresporeapro() {
		return this.nomresporeapro;
	}

	public void setNomresporeapro(String nomresporeapro) {
		this.nomresporeapro = nomresporeapro;
	}

	@Column(name = "PRENOMRESPOREAPRO", length = 40)
	public String getPrenomresporeapro() {
		return this.prenomresporeapro;
	}

	public void setPrenomresporeapro(String prenomresporeapro) {
		this.prenomresporeapro = prenomresporeapro;
	}

	@Column(name = "CIVILITE", length = 10)
	public String getCivilite() {
		return this.civilite;
	}

	public void setCivilite(String civilite) {
		this.civilite = civilite;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEDEBUTEMBAUCHE", length = 10)
	public Date getDatedebutembauche() {
		return this.datedebutembauche;
	}

	public void setDatedebutembauche(Date datedebutembauche) {
		this.datedebutembauche = datedebutembauche;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEFINEMBAUCHE", length = 10)
	public Date getDatefinembauche() {
		return this.datefinembauche;
	}

	public void setDatefinembauche(Date datefinembauche) {
		this.datefinembauche = datefinembauche;
	}

	@Column(name = "SALAIRE", precision = 12, scale = 0)
	public Float getSalaire() {
		return this.salaire;
	}

	public void setSalaire(Float salaire) {
		this.salaire = salaire;
	}

	@Column(name = "FONCTION", length = 30)
	public String getFonction() {
		return this.fonction;
	}

	public void setFonction(String fonction) {
		this.fonction = fonction;
	}

}
